"""Initial database schema

Revision ID: 498dde8da588
Revises: 
Create Date: 2026-01-16 09:32:12.683013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498dde8da588'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_programs',
    sa.Column('organization_context', sa.String(length=255), nullable=False),
    sa.Column('time_period', sa.DateTime(), nullable=False),
    sa.Column('responsible_team', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_programs_created_at'), 'evaluation_programs', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluation_programs_id'), 'evaluation_programs', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_programs_is_active'), 'evaluation_programs', ['is_active'], unique=False)
    op.create_table('llm_tool_configurations',
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=False),
    sa.Column('prompt_strategy', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('total_score_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_tool_configurations_created_at'), 'llm_tool_configurations', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_tool_configurations_id'), 'llm_tool_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_llm_tool_configurations_is_active'), 'llm_tool_configurations', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='External identity provider user ID (Keycloak sub)'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='User email from identity provider'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Full name from identity provider'),
    sa.Column('bio', sa.Text(), nullable=True, comment='User biography/description (app-specific)'),
    sa.Column('notification_preferences', sa.String(length=500), nullable=True, comment='JSON string of notification preferences'),
    sa.Column('theme_preference', sa.String(length=50), nullable=True, comment='UI theme preference: light, dark, system'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('goals',
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('focus', sa.String(length=255), nullable=False),
    sa.Column('viewpoint', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('evaluation_program_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_program_id'], ['evaluation_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_created_at'), 'goals', ['created_at'], unique=False)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_is_active'), 'goals', ['is_active'], unique=False)
    op.create_table('evaluation_criteria',
    sa.Column('dimension', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('aggregation_strategy', sa.String(length=50), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_criteria_created_at'), 'evaluation_criteria', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluation_criteria_id'), 'evaluation_criteria', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_criteria_is_active'), 'evaluation_criteria', ['is_active'], unique=False)
    op.create_table('aggregated_scores',
    sa.Column('criterion_id', sa.UUID(), nullable=False),
    sa.Column('tool_config_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('component_metrics', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['evaluation_criteria.id'], ),
    sa.ForeignKeyConstraint(['tool_config_id'], ['llm_tool_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregated_scores_created_at'), 'aggregated_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_aggregated_scores_id'), 'aggregated_scores', ['id'], unique=False)
    op.create_index(op.f('ix_aggregated_scores_is_active'), 'aggregated_scores', ['is_active'], unique=False)
    op.create_table('metrics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('scale_type', sa.String(length=20), nullable=False),
    sa.Column('collection_method', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('evaluation_criterion_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_criterion_id'], ['evaluation_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_created_at'), 'metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_is_active'), 'metrics', ['is_active'], unique=False)
    op.create_table('measurements',
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('normalized_value', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('evaluator', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('llm_tool_configuration_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('aggregated_score_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aggregated_score_id'], ['aggregated_scores.id'], ),
    sa.ForeignKeyConstraint(['llm_tool_configuration_id'], ['llm_tool_configurations.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_created_at'), 'measurements', ['created_at'], unique=False)
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    op.create_index(op.f('ix_measurements_is_active'), 'measurements', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_is_active'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_created_at'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_metrics_is_active'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_created_at'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_aggregated_scores_is_active'), table_name='aggregated_scores')
    op.drop_index(op.f('ix_aggregated_scores_id'), table_name='aggregated_scores')
    op.drop_index(op.f('ix_aggregated_scores_created_at'), table_name='aggregated_scores')
    op.drop_table('aggregated_scores')
    op.drop_index(op.f('ix_evaluation_criteria_is_active'), table_name='evaluation_criteria')
    op.drop_index(op.f('ix_evaluation_criteria_id'), table_name='evaluation_criteria')
    op.drop_index(op.f('ix_evaluation_criteria_created_at'), table_name='evaluation_criteria')
    op.drop_table('evaluation_criteria')
    op.drop_index(op.f('ix_goals_is_active'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_created_at'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_llm_tool_configurations_is_active'), table_name='llm_tool_configurations')
    op.drop_index(op.f('ix_llm_tool_configurations_id'), table_name='llm_tool_configurations')
    op.drop_index(op.f('ix_llm_tool_configurations_created_at'), table_name='llm_tool_configurations')
    op.drop_table('llm_tool_configurations')
    op.drop_index(op.f('ix_evaluation_programs_is_active'), table_name='evaluation_programs')
    op.drop_index(op.f('ix_evaluation_programs_id'), table_name='evaluation_programs')
    op.drop_index(op.f('ix_evaluation_programs_created_at'), table_name='evaluation_programs')
    op.drop_table('evaluation_programs')
    # ### end Alembic commands ###
