"""add_ecosystem_and_validity_fields

Revision ID: a67544ca8007
Revises: 498dde8da588
Create Date: 2026-02-05 08:13:30.646051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67544ca8007'
down_revision: Union[str, None] = '498dde8da588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_programs', sa.Column('validity_period', sa.Integer(), nullable=True))
    op.add_column('evaluation_programs', sa.Column('reevaluation_triggers', sa.JSON(), nullable=True))
    op.add_column('llm_tool_configurations', sa.Column('toolchain', sa.String(length=500), nullable=True))
    op.add_column('llm_tool_configurations', sa.Column('ide', sa.String(length=255), nullable=True))
    op.add_column('llm_tool_configurations', sa.Column('ide_plugins', sa.JSON(), nullable=True))
    op.add_column('llm_tool_configurations', sa.Column('conversation_history', sa.JSON(), nullable=True))
    op.add_column('llm_tool_configurations', sa.Column('skills_used', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_tool_configurations', 'skills_used')
    op.drop_column('llm_tool_configurations', 'conversation_history')
    op.drop_column('llm_tool_configurations', 'ide_plugins')
    op.drop_column('llm_tool_configurations', 'ide')
    op.drop_column('llm_tool_configurations', 'toolchain')
    op.drop_column('evaluation_programs', 'reevaluation_triggers')
    op.drop_column('evaluation_programs', 'validity_period')
    # ### end Alembic commands ###
